---
- name: install aide packages
  yum:
    name: aide
  tags: aide

- name: copy aide.conf
  template:
    src: aide.conf.j2
    dest: /etc/aide.conf
    mode: 0600
  tags: aide

- name: set aide database
  shell: aide --init; mv /var/lib/aide/aide.db{.new,}.gz
  args:
    creates: /var/lib/aide/aide.db.gz
  tags: aide
